# Generated by Django 2.2.19 on 2022-04-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
